{
  config,
  lib,
  self,
  pkgs,
  ...
}:
with lib;
let
  unit = "affine";
  srv = config.server;
  cfg = config.server.services.${unit};
  domain = "${cfg.subdomain}.${srv.infra.www.url}";
  rev = "stable";
in
{
  config = mkIf (srv.infra.podman.enable && cfg.enable) {
    age.secrets = {
      affineEnvironment.file = "${self}/secrets/affineEnvironment.age";
    };

    networking.firewall = {
      allowedTCPPorts = [
        5353
        5432
      ];
      allowedUDPPorts = [
        5353
        5432
      ];
    };

    system.activationScripts.affine-dirs = ''
      mkdir -p -m 0755 ${cfg.configDir}/{storage,config,redis}
      mkdir -p -m 0700 ${cfg.configDir}/postgres
    '';

    systemd = {
      services = {
        "podman-network-affine-default" = {
          path = [ pkgs.podman ];
          serviceConfig = {
            Type = "oneshot";
            RemainAfterExit = true;
            ExecStop = "podman network rm -f affine-default";
          };
          script = ''
            podman network inspect affine-default || podman network create affine-default
          '';
          partOf = [ "podman-compose-affine-root.target" ];
          wantedBy = [ "podman-compose-affine-root.target" ];
        };

        "podman-affine" = {
          serviceConfig = {
            Restart = lib.mkOverride 90 "always";
            RestartMaxDelaySec = lib.mkOverride 90 "1m";
            RestartSec = lib.mkOverride 90 "100ms";
            RestartSteps = lib.mkOverride 90 9;
          };
          after = [
            "podman-network-affine-default.service"
          ];
          requires = [
            "podman-network-affine-default.service"
          ];
          partOf = [
            "podman-compose-affine-root.target"
          ];
          wantedBy = [
            "podman-compose-affine-root.target"
          ];
        };

        "podman-affine-postgres" = {
          serviceConfig = {
            Restart = lib.mkOverride 90 "always";
            RestartMaxDelaySec = lib.mkOverride 90 "1m";
            RestartSec = lib.mkOverride 90 "100ms";
            RestartSteps = lib.mkOverride 90 9;
          };
          after = [
            "podman-network-affine-default.service"
          ];
          requires = [
            "podman-network-affine-default.service"
          ];
          partOf = [
            "podman-compose-affine-root.target"
          ];
          wantedBy = [
            "podman-compose-affine-root.target"
          ];
        };

        "podman-affine-redis" = {
          serviceConfig = {
            Restart = lib.mkOverride 90 "always";
            RestartMaxDelaySec = lib.mkOverride 90 "1m";
            RestartSec = lib.mkOverride 90 "100ms";
            RestartSteps = lib.mkOverride 90 9;
          };
          after = [
            "podman-network-affine-default.service"
          ];
          requires = [
            "podman-network-affine-default.service"
          ];
          partOf = [
            "podman-compose-affine-root.target"
          ];
          wantedBy = [
            "podman-compose-affine-root.target"
          ];
        };

        "podman-affine-migration" = {
          serviceConfig = {
            Restart = lib.mkOverride 90 "no";
          };
          after = [
            "podman-network-affine-default.service"
          ];
          requires = [
            "podman-network-affine-default.service"
          ];
          partOf = [
            "podman-compose-affine-root.target"
          ];
          wantedBy = [
            "podman-compose-affine-root.target"
          ];
        };

        "podman-compose-affine-root" = {
          unitConfig = {
            Description = "Root target generated by compose2nix.";
          };
          wantedBy = [ "multi-user.target" ];
        };
      };
    };

    virtualisation.oci-containers.containers = {
      affine = {
        image = "ghcr.io/toeverything/affine:${rev}";
        ports = [ "127.0.0.1:${toString cfg.port}:${toString cfg.port}" ];
        dependsOn = [
          "affine-postgres"
          "affine-redis"
          "affine-migration"
        ];
        volumes = [
          "${cfg.configDir}/storage:/root/.affine/storage"
          "${cfg.configDir}/config:/root/.affine/config"
        ];
        environment = {
          AFFINE_REVISION = "stable";
          AFFINE_SERVER_PORT = "${toString cfg.port}";
          AFFINE_SERVER_HOST = domain;
          AFFINE_SERVER_HTTPS = "true";
          AFFINE_INDEXER_ENABLED = "false";
          REDIS_SERVER_HOST = "affine-redis";
        };
        environmentFiles = [ config.age.secrets.affineEnvironment.path ];
        extraOptions = [
          "--network-alias=affine"
          "--network=affine-default"
        ];
      };

      affine-postgres = {
        image = "pgvector/pgvector:pg16";
        volumes = [
          "${cfg.configDir}/postgres:/var/lib/postgresql/data"
        ];
        environment = {
          # POSTGRES_HOST_AUTH_METHOD = "trust";
          POSTGRES_INITDB_ARGS = "--data-checksums";
        };
        environmentFiles = [ config.age.secrets.affineEnvironment.path ];
        extraOptions = [
          "--health-cmd=pg_isready -U ${unit} -d ${unit}"
          "--health-interval=10s"
          "--health-timeout=5s"
          "--health-retries=5"
          "--network-alias=affine-postgres"
          "--network=affine-default"
        ];
      };

      affine-redis = {
        image = "redis:7";
        volumes = [
          "${cfg.configDir}/redis:/data"
        ];
        # networks = [ "affine-net" ];
        extraOptions = [
          "--health-cmd=redis-cli --raw incr ping"
          "--health-interval=10s"
          "--health-timeout=5s"
          "--health-retries=5"
          "--network-alias=affine-redis"
          "--network=affine-default"
        ];
      };

      affine-migration = {
        image = "ghcr.io/toeverything/affine:${rev}";
        dependsOn = [
          "affine-postgres"
          "affine-redis"
        ];
        volumes = [
          "${cfg.configDir}/storage:/root/.affine/storage"
          "${cfg.configDir}/config:/root/.affine/config"
        ];
        cmd = [
          "sh"
          "-c"
          "node ./scripts/self-host-predeploy.js"
        ];
        environment = {
          REDIS_SERVER_HOST = "affine-redis";
          AFFINE_INDEXER_ENABLED = "false";
        };
        environmentFiles = [ config.age.secrets.affineEnvironment.path ];
        extraOptions = [
          "--network-alias=affine-migration"
          "--network=affine-default"
        ];
      };
    };
  };
}
