image: alpine/edge
secrets:
  - 600028fa-bd09-4579-aa75-0ebf31d41dab
sources:
  - git@git.sr.ht:~canasta/cnix
environment:
  GIT_SSH_COMMAND: ssh -o StrictHostKeyChecking=no
tasks:
  - setup: |
      # This is for not having to cd into your <repo> for each task
      echo 'cd <repo>' >> ~/.buildenv
  - check: |
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - mirror: |
      git push --force --mirror git@github.com:cnsta/cnix.git
