{umodPath, ...}: {
  imports = [
    "${umodPath}/devtools/nixvim/plugins/barbar.nix"
    "${umodPath}/devtools/nixvim/plugins/comment.nix"
    "${umodPath}/devtools/nixvim/plugins/conform.nix"
    "${umodPath}/devtools/nixvim/plugins/cmp.nix"
    "${umodPath}/devtools/nixvim/plugins/copilot.nix"
    "${umodPath}/devtools/nixvim/plugins/efm.nix"
    "${umodPath}/devtools/nixvim/plugins/floaterm.nix"
    "${umodPath}/devtools/nixvim/plugins/harpoon.nix"
    "${umodPath}/devtools/nixvim/plugins/lsp.nix"
    "${umodPath}/devtools/nixvim/plugins/lualine.nix"
    "${umodPath}/devtools/nixvim/plugins/lightline.nix"
    "${umodPath}/devtools/nixvim/plugins/markdown-preview.nix"
    "${umodPath}/devtools/nixvim/plugins/neo-tree.nix"
    "${umodPath}/devtools/nixvim/plugins/nonels.nix"
    "${umodPath}/devtools/nixvim/plugins/rustaceanvim.nix"
    "${umodPath}/devtools/nixvim/plugins/startify.nix"
    "${umodPath}/devtools/nixvim/plugins/tagbar.nix"
    "${umodPath}/devtools/nixvim/plugins/telescope.nix"
    "${umodPath}/devtools/nixvim/plugins/treesitter.nix"
    "${umodPath}/devtools/nixvim/plugins/vimtex.nix"
    "${umodPath}/devtools/nixvim/plugins/yanky.nix"
  ];
}
