name: Mirror repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Mirror to SourceHut
        run: |
          git remote set-url --add --push origin git@git.sr.ht:~canasta/cnix
          git remote set-url --push origin --mirror=push
          git push --mirror
